name: ci

on: workflow_dispatch

env:
  DOCKERHUB_URL: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORYNAME }}:${{ github.sha }} 
  
jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_URL }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  

  docker_run:
    runs-on: self-hosted
    needs: docker_push
    env:
      GITHUB_REPOSITORYNAME: ${{ github.event.repository.name }}
    steps:
    - name: Remove previous version
      timeout-minutes: 120
      run: |
          docker stop $GITHUB_REPOSITORYNAME || true
          docker rm $GITHUB_REPOSITORYNAME || true
    - name: Docker start
      timeout-minutes: 180
      run: |
        docker run -d \
        --link mongo_${{ github.event.repository.owner.login }}:mongo \
        -e API_KEY=${{ secrets.API_KEY }} \
        -e TOKEN=${{ secrets.TOKEN }} \
        -e MONGO=${{ secrets.MONGO }} \
        -e ADMIN_ID=${{ secrets.ADMIN_ID }} \
        --name $GITHUB_REPOSITORYNAME \
        $DOCKERHUB_URL